title: Transit timing en masse
author: Ekaterina Ivshina & Josh Winn
email: ivshina@princeton.edu
description: A clean and responsive jekyll theme

github_username: transit-timing
# twitter_username:
# facebook_username:
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:

blog_theme: light
# light-theme-accent-color: '#333'
# dark-theme-accent-color: '#eee'

markdown: kramdown

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  # parse markdown inside block-level HTML tag
  parse_block_html: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag
theme: jekyll-theme-minimal
